ecs_cluster="aetion"
aws_access_key_id = "ABCDEFGHIJ" # Write our AWS cli credentials here
aws_secret_access_key = "password" # write your password here
region = "us-east-1"
nyc_vpc = "aetion-vpc"
vpc_network_cidr = "10.0.0.0/16"
public_01_cidr = "10.0.1.0/24"
public_02_cidr = "10.0.2.0/24"
max_instance_size = "4"
min_instance_size = "2"
desired_capacity = "2"
